image: barichello/godot-ci:3.2.3

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - test
  - deploy

variables:
  EXPORT_NAME: test-project

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - cd $EXPORT_NAME
    - godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

linux-release:
  stage: deploy
  dependencies:
    - linux
    - tests
  script:
    - rm -rf release/linux
    - mkdir -v -p release/linux
    - cp -r build/linux release/linux
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - release/linux

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - cd $EXPORT_NAME
    - godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

windows-release:
  stage: deploy
  dependencies:
    - windows
    - tests
  script:
    - rm -rf release/windows
    - mkdir -v -p release/windows
    - cp -r build/windows release/windows
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - release/windows

mac:
  stage: export
  script:
    - mkdir -v -p build/mac
    - cd $EXPORT_NAME
    - godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac

mac-release:
  stage: deploy
  dependencies:
    - mac
    - tests
  script:
    - rm -rf release/mac
    - mkdir -v -p release/mac
    - cp -r build/mac release/mac
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - release/mac

web:
  stage: export
  script:
    - mkdir -v -p build/web
    - cd $EXPORT_NAME
    - godot -v --export "HTML5" ../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

pages:
  stage: deploy
  dependencies:
    - web
    - tests
  script:
    - rm -rf public
    - cp -r build/web public
  artifacts:
    paths:
      - public

tests:
  stage: test
  dependencies:
    - web
    - mac
    - linux
    - windows
  script:
    - echo Stage for automated tests for builds.